language: ruby
rvm:
  # CentOS 6 is still stuck on this
  - 1.8.7
  - 1.9.3
  # CentOS 7 uses Ruby 2.0.0
  - 2.0.0
  # This is the latest stable MRI Ruby right now
  - 2.3.1
notifications:
  email:
   - raphael.pinson@camptocamp.com
install:
  # Use latest Augeas
  - sudo add-apt-repository -y ppa:raphink/augeas
  - sudo apt-get update
  - sudo apt-get install libaugeas-dev libxml2-dev
  - bundle install
